
version: 2

sources:
    - name: staging
      # For BigQuery:
      # database: dtc-de-course-339918
      database: dtc-de-course-339918
      # For Postgres:
      # database: production
      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata
        - name: external_fhv_tripdata
        # freshness:
          # error_after: {count: 6, period: hour}

models:
  - name: staging_green_tripdata
    description: >
      Trip made by Green taxis, also known as Boro taxis and street-hail liveries.
      Green taxis may respond to street hails, but only in the areas indicated in green on the
      map (i.e. above W 110 St/E 96th St in Manhattan and in the boroughs).
      The records were collected and provided to the New York City Taxi and Limousine Commission (TLC) by
      technology service providers.
    columns:
      - name: tripid
        description: Primary key for this table, generated with a concatenation of vendorid + pickup_datetime
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: VendorID
        description: >
          A code indicating the TPEP provider that provided the record.
          1 = Creative Mobile Technologies, LLC
          2 = VeriFone Inc.
      - name: pickup_datetime
        description: The date and time when the meter was engaged.
      - name: dropoff_datetime
        description: The date and time when the meter was disengaged.
      - name: passenger_count
        description: The number of passengers in the vehicle.  This is a driver-entered value.
      - name: trip_distance
        description: The elapsed trip distance in miles reported by the taximeter.
      - name: pickup_locationID
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: dropoff_locationID
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
      - name: rateCodeID
        description: >
          The final rate code in effect at the end of the trip.
            1 = standard rate
            2 = JFK
            3 = Newark
            4 = Nassau or Westchester
            5 = Negotiated fare
            6 = Group ride
      - name: store_and_fwd_flag
        description: >
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor, aka "store and forward,"
          because the vehicle did not have a connection to the server.
            Y = store and forward trip
            N = not a store and forward trip
      - name: dropoff_longitude
        description: Longitude where teh meter was disengaged.
      - name: dropoff_latitude
        description: Latitude where the meter was disengaged.
      - name: payment_type
        description: A numeric code signifying how the passenger paid for the trip
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false
      - name: payment_type_description
        description: Description of the payment_type code
      - name: fare_amount
        description: >
          The time and distance fare calculated by the meter.
          Extra miscellaneous extras and surcharges.  Currently, this only includes
          the $0.50 and $1 rush hour and overnight charges.
          MTA_tax $0.50 MTA tax that is automatically triggered based on the metered
          rate in use.
      - name: improvement_surcharge
        description: >
          $0.30 improvement surcharge assessed trips at the flag drop.  The
          improvement surcharge began being levied in 2015.
      - name: tip_amount
        description: >
          Tip amount. This field is automatically populated for credit card
          tips. Cash tips are not included.
      - name: tolls_amount
        description: Total amount of all tolls paid in the trip.
      - name: total_amount
        description: The total amount charged to passengers. Does not include cash tips.
  

  - name: staging_yellow_tripdata
    description: >
      Trips made by New York City's iconic yellow taxis.
      Yellow taxis are the only vehicles permitted to respond to a street hail from a passenger inall five
      boroughs. They may also be hailed using an e-mail app like Curb or Arro.
      The records were collected and provided to the New York City Taxi and Limousine Commission (TLC) by
      technology service providers.
    columns:
      - name: tripID
        description: Primary key for this table, generated with a concatenation of vendorid + pickup_datetime
        tests:
          - unique: 
              severity: warn
          - not_null:
              severity: warn
      - name: VendorID
        description: >
          A code indicating the TPEP provider that provided the record.
          1 = Creative Mobile Technologies, LLC
          2 = VeriFone Inc.
      - name: pickup_datetime
        description: The date and time when the meter was engaged.
      - name: dropoff_datetime
        description: The date and time when the meter was disengaged.
      - name: passenger_count
        description: The number of passengers in the vehicle.  This is a driver-entered value.
      - name: trip_distance
        description: The elapsed trip distance in miles reported by the taximeter.
      - name: pickup_locationID
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: dropoff_locationID
        description: locationid where the meter was engaged.
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: RateCodeID
        description: >
          The final rate code in effect at the end of the trip.
            1 = standard rate
            2 = JFK
            3 = Newark
            4 = Nassau or Westchester
            5 = Negotiated fare
            6 = Group ride
      - name: store_and_fwd_flag
        description: >
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor, aka "store and forward,"
          because the vehicle did not have a connection to the server.
            Y = store and forward trip
            N = not a store and forward trip
      - name: dropoff_longitude
        description: Longitude where teh meter was disengaged.
      - name: dropoff_latitude
        description: Latitude where the meter was disengaged.
      - name: payment_type
        description: A numeric code signifying how the passenger paid for the trip
        tests:
          - accepted_values:
              values: "{{ var('payment_type_values') }}"
              severity: warn
              quote: false
      - name: payment_type_description
        description: Description of the payment_type code
      - name: fare_amount
        description: >
          The time and distance fare calculated by the meter.
          Extra miscellaneous extras and surcharges.  Currently, this only includes
          the $0.50 and $1 rush hour and overnight charges.
          MTA_tax $0.50 MTA tax that is automatically triggered based on the metered
          rate in use.
      - name: improvement_surcharge
        description: >
          $0.30 improvement surcharge assessed trips at the flag drop.  The
          improvement surcharge began being levied in 2015.
      - name: tip_amount
        description: >
          Tip amount. This field is automatically populated for credit card
          tips. Cash tips are not included.
      - name: tolls_amount
        description: Total amount of all tolls paid in the trip.
      - name: total_amount
        description: The total amount charged to passengers. Does not include cash tips.


  - name: staging_fhv_tripdata
    description: > 
      Data includes trip data from high-volume for-hire vehicle(FHV) bases (bases for
      companies dispatching 10,000+ trip per day; meaning Uber, Lyft, Via, and Juno),
      community livery bases, luxury limousine bases, and black car bases.
    columns:
      - name: dispatching_base_num
        description: The TLC base license number of the base that dispatched the trip.
      - name: pickup_datetime
        description: The date and time of the trip pick up.
      - name: dropoff_datetime
        description: The date and time of the trip drop off.
      - name: PULocationID
        description: TLC Taxi Zone in which the trip began.
      - name: DOLocationID
        description: TLC Taxi Zone in which the trip ended.
      - name: SR_Flag
        description: >
          Indicates if the trip was part of a shared ride chain offered by a
          High Volume FHV company (Uber Pool, Lyft Line). For shared trips,
          the value is 1. For non-shared rides, the field is null.

          NOTE: For most High Volume FHV companies, only shared rides that
          were requested AND matched to another shared-ride request over
          the course of the journey are flagged. However, Lyft (base license
          numbers B02510 + B02844) also flags rides for which a shared ride
          was requested but another passenger was not successfully matched
          to share the trip -- therefore, trip records with SR_Flag = 1 from those
          two bases could indicate EITHER a first trip in a shared trip chain OR
          a trip for which a shared ride was requested but never matched.
          Users should anticipate an overcount of successfully shared trips
          completed by Lyft.

